theme: jekyll-theme-cayman
title: theCaseFor
description: "“The important thing is not to stop questioning. Curiosity has its own reason for existence. One cannot help but be in awe when he contemplates the mysteries of eternity, of life, of the marvelous structure of reality.""
